# Generated by Django 3.2.9 on 2022-07-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='products',
        ),
        migrations.AddField(
            model_name='inventory',
            name='products',
            field=models.ManyToManyField(related_name='products', to='products.Product'),
        ),
    ]
