# Generated by Django 3.2.9 on 2022-09-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(default='./images/default_image.png', upload_to='', verbose_name='./images')),
            ],
        ),
    ]
