# Generated by Django 3.2.9 on 2022-09-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_images_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='path',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
    ]
