# Generated by Django 3.2.9 on 2022-09-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20220920_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='product',
        ),
    ]
