# Generated by Django 3.2.9 on 2022-09-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_remove_images_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='./images/default_image.png', upload_to='', verbose_name='./images'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_2',
            field=models.ImageField(null=True, upload_to='', verbose_name='./images'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_3',
            field=models.ImageField(null=True, upload_to='', verbose_name='./images'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_4',
            field=models.ImageField(null=True, upload_to='', verbose_name='./images'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_5',
            field=models.ImageField(null=True, upload_to='', verbose_name='./images'),
        ),
    ]
