# Generated by Django 3.2.9 on 2022-09-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_auto_20220920_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='./images/default_image.png', upload_to='./images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_2',
            field=models.ImageField(null=True, upload_to='./images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_3',
            field=models.ImageField(null=True, upload_to='./images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_4',
            field=models.ImageField(null=True, upload_to='./images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_5',
            field=models.ImageField(null=True, upload_to='./images'),
        ),
    ]
