# Generated by Django 3.2.9 on 2022-09-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_auto_20220920_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='products',
            name='subcategory',
        ),
    ]
