# Generated by Django 3.2.9 on 2022-09-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
